CloudConsulting/force-app/main/default/objects/Project__c/Project__c.object-meta.xml
<CustomObject>
    <label>Project</label>
    <nameField>
        <label>Project Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Projects</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

CloudConsulting/force-app/main/default/objects/Project_Line_Item__c/Project_Line_Item__c.object-meta.xml
<CustomObject>
    <label>Project Line Item</label>
    <nameField>
        <label>Project Line Item Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Project Line Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

CloudConsulting/force-app/main/default/objects/Project_Line_Item__c/fields/HoursAllocated__c.field-meta.xml
<CustomField>
    <fullName>HoursAllocated__c</fullName>
    <label>HoursAllocated</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

CloudConsulting/force-app/main/default/objects/Project_Line_Item__c/fields/HoursPending__c.field-meta.xml
<CustomField>
    <fullName>HoursPending__c</fullName>
    <formula>HoursPerRole__c -  HoursAllocated__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>HoursPending</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

CloudConsulting/force-app/main/default/objects/Project_Line_Item__c/fields/HoursPerRole__c.field-meta.xml
<CustomField>
    <fullName>HoursPerRole__c</fullName>
    <label>HoursPerRole</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

CloudConsulting/force-app/main/default/objects/Project_Line_Item__c/fields/TaskHoursPending__c.field-meta.xml
<CustomField>
    <fullName>TaskHoursPending__c</fullName>
    <formula>HoursPerRole__c -  TaskHoursAllocated__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>TaskHoursPending</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

CloudConsulting/force-app/main/default/objects/Project_Resources__c/Project_Resources__c.object-meta.xml
<CustomObject>
    <label>Project Resource</label>
    <nameField>
        <displayFormat>PR-{0000}</displayFormat>
        <label>Project Resources Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Project Resources</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

CloudConsulting/force-app/main/default/objects/Project_Resources__c/fields/HoursAllocated__c.field-meta.xml
<CustomField>
    <fullName>HoursAllocated__c</fullName>
    <label>HoursAllocated</label>
    <summarizedField>Task__c.EstimatedHours__c</summarizedField>
    <summaryForeignKey>Task__c.Project_Resource__c</summaryForeignKey>
    <summaryOperation>sum</summaryOperation>
    <type>Summary</type>
</CustomField>

CloudConsulting/force-app/main/default/objects/Project_Resources__c/fields/Project__c.field-meta.xml
<CustomField>
    <fullName>Project__c</fullName>
    <label>Project</label>
    <referenceTo>Project__c</referenceTo>
    <relationshipLabel>Project Resources</relationshipLabel>
    <relationshipName>Project_Resources</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

CloudConsulting/force-app/main/default/objects/Project_Resources__c/fields/Project_Line_Item__c.field-meta.xml
<CustomField>
    <fullName>Project_Line_Item__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Project Line Item</label>
    <referenceTo>Project_Line_Item__c</referenceTo>
    <relationshipLabel>Project Resources</relationshipLabel>
    <relationshipName>Project_Resources</relationshipName>
    <type>Lookup</type>
</CustomField>

CloudConsulting/force-app/main/default/objects/Project_Resources__c/fields/RequieredHours__c.field-meta.xml
<CustomField>
    <fullName>RequieredHours__c</fullName>
    <label>RequieredHours</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

CloudConsulting/force-app/main/default/objects/Project_Resources__c/fields/User__c.field-meta.xml
<CustomField>
    <fullName>User__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>User</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Project_Resources</relationshipName>
    <type>Lookup</type>
</CustomField>

CloudConsulting/force-app/main/default/objects/Task__c/Task__c.object-meta.xml
<CustomObject>
    <label>Task</label>
    <nameField>
        <displayFormat>T-{0000}</displayFormat>
        <label>Task Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Tasks</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

CloudConsulting/force-app/main/default/objects/Task__c/fields/EstimatedHours__c.field-meta.xml
<CustomField>
    <fullName>EstimatedHours__c</fullName>
    <label>EstimatedHours</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

CloudConsulting/force-app/main/default/objects/Task__c/fields/Project_Resource__c.field-meta.xml
<CustomField>
    <fullName>Project_Resource__c</fullName>
    <label>Project Resource</label>
    <referenceTo>Project_Resources__c</referenceTo>
    <relationshipLabel>Tasks</relationshipLabel>
    <relationshipName>Tasks</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

CloudConsulting/force-app/main/default/objects/Task__c/fields/WorkedHours__c.field-meta.xml
<CustomField>
    <fullName>WorkedHours__c</fullName>
    <defaultValue>0</defaultValue>
    <label>WorkedHoursTask</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

CloudConsulting/force-app/main/default/classes/assingTask.cls
public with sharing class assingTask {

    public class UserWrapper{
        @AuraEnabled
        public String prId { get; set;}
        @AuraEnabled
        public String FirstName { get; set;}
        @AuraEnabled
        public String LastName{ get; set;} 
        @AuraEnabled
        public Decimal RequieredHours{ get; set;} 
        @AuraEnabled
        public Decimal HoursAllocated{ get; set;} 
        
    }  
    
     //List of available employees by role
 /*@AuraEnabled(cacheable=true)
 public static List <AggregateResult> getAvailableEmployeesByRole (String roleName, String projectId){

        List<AggregateResult> resources = 
        [
            SELECT  User__c Id, 
                    User__r.FirstName FN, 
                    User__r.LastName LN,                      
                    SUM(RequieredHours__c) AllocatedHours
                    FROM Project_Resources__c 
                    WHERE Project__c = : projectId
                    AND Project_Line_Item__r.Role__c = : roleName
                    GROUP BY    User__c, 
                                User__r.FirstName, 
                                User__r.LastName 
                                
        ];

        return resources;
        
 }*/

  //List of the roles with pending time to be assigned for tasks
  @AuraEnabled(cacheable=true)
  public static List <Project_Line_Item__c> getRolesWhithoutAssignment (Id projectId) {
   List<Project_Line_Item__c> rolesWithoutAssignment =
                   [
                   SELECT Id, Role__c, HoursPending__c, HoursPerRole__c, HoursAllocated__c 
                   FROM Project_Line_Item__c 
                   WHERE Project__c = : projectId
                   AND TaskHoursPending__c > 0     
                   ];
         
   return rolesWithoutAssignment; 
 }

 @AuraEnabled(cacheable=true)
 public static List <Project_Line_Item__c> getHoursPendingByRole (Id projectId, String roleName) {
   List <Project_Line_Item__c> hoursPending = 
                   [
                   SELECT TaskHoursPending__c
                   FROM Project_Line_Item__c
                   WHERE Project__c = : projectId
                   //AND HoursPending__c > 0
                   AND Role__c = : roleName
                   ];
               
   return hoursPending; 
 }

 @AuraEnabled(cacheable=true)
 public static List <UserWrapper> getAvailableEmployeesByRole (String roleName, String projectId){

        System.debug('Rol ' + roleName);
        System.debug('Project Id ' + projectId);
        List<Project_Resources__c> resources = 
        [
            SELECT  User__c, 
                    User__r.FirstName, 
                    User__r.LastName,                      
                    RequieredHours__c,
                    HoursAllocated__c,
                    StartDate__c
                    FROM Project_Resources__c 
                    WHERE Project__c = : projectId
                    AND Project_Line_Item__r.Role__c = : roleName
                    
                                
        ];
        System.debug('Resource ' + resources[0]);
        List<UserWrapper> resourcesChild = new List<UserWrapper>();
                    
            
                for(Project_Resources__c childIns : resources) {

                    UserWrapper rchild = new UserWrapper();
   
                    rchild.prId = childIns.Id;
                    rchild.FirstName = childIns.User__r.FirstName;
                    rchild.LastName= childIns.User__r.LastName;
                    rchild.RequieredHours= childIns.RequieredHours__c;
                    rchild.HoursAllocated= childIns.HoursAllocated__c;
                    if(rchild.RequieredHours>rchild.HoursAllocated){                
                    resourcesChild.add(rchild);
                    }

             }
             System.debug('Resource Child ' + resourcesChild[0]);  
        return resourcesChild;
        
 }

 @AuraEnabled
 public static void assingTasks(String assingTaskJSON){

   List<Task__c> allTask = (List<Task__c>) JSON.deserialize(assingTaskJSON, List<Task__c>.class);

   Set<Id> prTask = New Set<Id>();
   for(Task__c aTask : allTask){
    System.debug('debug ' + aTask);
    prTask.add(aTask.Project_Resource__c);
   }
   System.debug('Set ID ' + prTask);
   
   /*List<Project_Resources__c> prDates =
                        [
                        SELECT StartDate__c
                        FROM Project_Resources__c
                        WHERE Id IN: prTask
                        ];

    for(Project_Resources__c aTask : prDates){
        System.debug('Dates ' + aTask);
    }*/

    Map<Id,Project_Resources__c> prDatesMap = New Map<Id,Project_Resources__c>([
        SELECT  StartDate__c,
                RequieredHours__c,
                HoursAllocated__c
        FROM Project_Resources__c
        WHERE Id IN: prTask
        ]);

    System.debug('Dates Map ' + prDatesMap);

    //Integer rou = Math.round(100/49);
    //Integer rest = Math.mod(100, 97);
    //System.debug('Round ' + rou);
    //System.debug('Rest ' + rest);

    for(Task__c aTask : allTask){
        
        
        Integer allocated = Integer.valueOf(prDatesMap.get(aTask.Project_Resource__c).HoursAllocated__c);
        Integer estimated = Integer.valueOf(aTask.EstimatedHours__c);
                
        Integer cAllocated = Math.round(allocated/10);
        aTask.StartDate__c = prDatesMap.get(aTask.Project_Resource__c).StartDate__c + cAllocated;
        Integer cEstimated = Math.round(aTask.EstimatedHours__c/10);
        aTask.EndDate__c = aTask.StartDate__c + cEstimated;    
        aTask.WorkedHours__c = 0;  
            
               
        //aTask.StartDate__c = prDatesMap.get(aTask.Project_Resource__c).StartDate__c;        
    }

    for(Task__c aTask : allTask){
        System.debug('debug date' + aTask);       
    }
    
   insert allTask;
   
   
 }

}