CloudConsulting/force-app/main/default/objects/Project__c/Project__c.object-meta.xml
<CustomObject>
    <label>Project</label>
    <nameField>
        <label>Project Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Projects</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

CloudConsulting/force-app/main/default/objects/Project__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Pre Kickoff</fullName>
            </value>
            <value>
                <fullName>In Progress</fullName>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

CloudConsulting/force-app/main/default/objects/Project_Resources__c/Project_Resources__c.object-meta.xml
<CustomObject>
    <label>Project Resource</label>
    <nameField>
        <displayFormat>PR-{0000}</displayFormat>
        <label>Project Resources Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Project Resources</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

CloudConsulting/force-app/main/default/objects/Project_Resources__c/fields/Project__c.field-meta.xml
<CustomField>
    <fullName>Project__c</fullName>
    <label>Project</label>
    <referenceTo>Project__c</referenceTo>
    <relationshipLabel>Project Resources</relationshipLabel>
    <relationshipName>Project_Resources</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

CloudConsulting/force-app/main/default/objects/Project_Resources__c/fields/User__c.field-meta.xml
<CustomField>
    <fullName>User__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>User</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Project_Resources</relationshipName>
    <type>Lookup</type>
</CustomField>

CloudConsulting/force-app/main/default/objects/Task__c/Task__c.object-meta.xml
<CustomObject>
    <label>Task</label>
    <nameField>
        <displayFormat>T-{0000}</displayFormat>
        <label>Task Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Tasks</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

CloudConsulting/force-app/main/default/objects/Task__c/fields/EstimatedHours__c.field-meta.xml
<CustomField>
    <fullName>EstimatedHours__c</fullName>
    <label>EstimatedHours</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

CloudConsulting/force-app/main/default/objects/Task__c/fields/Project_Resource__c.field-meta.xml
<CustomField>
    <fullName>Project_Resource__c</fullName>
    <label>Project Resource</label>
    <referenceTo>Project_Resources__c</referenceTo>
    <relationshipLabel>Tasks</relationshipLabel>
    <relationshipName>Tasks</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

CloudConsulting/force-app/main/default/objects/Task__c/fields/WorkedHours__c.field-meta.xml
<CustomField>
    <fullName>WorkedHours__c</fullName>
    <defaultValue>0</defaultValue>
    <label>WorkedHoursTask</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

CloudConsulting/force-app/main/default/classes/Workload.cls
public class Workload {
    @AuraEnabled(cacheable=true)
    public static list<Project_Resources__c> getProject (){
        Id uId = UserInfo.getUserId();
        List<Project_Resources__c> projects = [SELECT Id,
                                               			Project__c,
                                                       Project__r.Name,
                                                       Name,
                                                       User__c
                                              FROM Project_Resources__c
                                              WHERE User__c =: uId];
        System.debug(projects.get(0).Project__r.Name);
        return projects;   
        
    }
    
	@AuraEnabled(cacheable=true)
    public static list<Task__c> getTask (Id projectResourceId){
        List<Task__c> tasks= [SELECT Id,
                                      Status__c,
                                      Description__c,
                                      StartDate__c,
                                      EndDate__c,
                                      EstimatedHours__c,
                                      WorkedHours__c,
                              			Project_Resource__c
                                FROM Task__c
                                WHERE Project_Resource__c =: projectResourceId
                             	ORDER BY Project_Resource__c];
        System.debug(tasks.get(0).Description__c);
        return tasks;
    } 
    
    @AuraEnabled(cacheable=false)
    public static Task__c updateWorkedHours (Id taskId, Boolean completed, Integer workedHours){
        system.debug(taskId);
        Task__c task = [SELECT Id,
                                Status__c,
                                Description__c,
                                StartDate__c,
                                EndDate__c,
                                EstimatedHours__c,
                                WorkedHours__c,
                                Project_Resource__c
                        FROM Task__c
                       	WHERE Id =: taskId];
        
        task.Status__c = completed == true ? 'Completed': 'In Progress';
        task.WorkedHours__c += workedHours;
        
        update task;
        
        return task;
    }
}