CloudConsulting/force-app/main/default/objects/Project__c/Project__c.object-meta.xml
<CustomObject>
    <label>Project</label>
    <nameField>
        <label>Project Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Projects</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

CloudConsulting/force-app/main/default/objects/Project__c/fields/ProjectManager__c.field-meta.xml
<CustomField>
    <fullName>ProjectManager__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>ProjectManager</label>
    <referenceTo>User</referenceTo>
    <relationshipName>ProjectManagers</relationshipName>
    <type>Lookup</type>
</CustomField>

CloudConsulting/force-app/main/default/objects/Project__c/fields/QuantityHours__c.field-meta.xml
<CustomField>
    <fullName>QuantityHours__c</fullName>
    <label>QuantityHours</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

CloudConsulting/force-app/main/default/objects/Project__c/fields/SquadLead__c.field-meta.xml
<CustomField>
    <fullName>SquadLead__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>SquadLead</label>
    <referenceTo>User</referenceTo>
    <relationshipName>SquadLeads</relationshipName>
    <type>Lookup</type>
</CustomField>

CloudConsulting/force-app/main/default/objects/Project__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Pre Kickoff</fullName>
            </value>
            <value>
                <fullName>In Progress</fullName>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

CloudConsulting/force-app/main/default/objects/Project_Line_Item__c/Project_Line_Item__c.object-meta.xml
<CustomObject>
    <label>Project Line Item</label>
    <nameField>
        <label>Project Line Item Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Project Line Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

CloudConsulting/force-app/main/default/objects/Project_Line_Item__c/fields/HoursPerRole__c.field-meta.xml
<CustomField>
    <fullName>HoursPerRole__c</fullName>
    <label>HoursPerRole</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

CloudConsulting/force-app/main/default/objects/Project_Resources__c/Project_Resources__c.object-meta.xml
<CustomObject>
    <label>Project Resource</label>
    <nameField>
        <displayFormat>PR-{0000}</displayFormat>
        <label>Project Resources Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Project Resources</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

CloudConsulting/force-app/main/default/objects/Project_Resources__c/fields/Project__c.field-meta.xml
<CustomField>
    <fullName>Project__c</fullName>
    <label>Project</label>
    <referenceTo>Project__c</referenceTo>
    <relationshipLabel>Project Resources</relationshipLabel>
    <relationshipName>Project_Resources</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

CloudConsulting/force-app/main/default/objects/Project_Resources__c/fields/Project_Line_Item__c.field-meta.xml
<CustomField>
    <fullName>Project_Line_Item__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Project Line Item</label>
    <referenceTo>Project_Line_Item__c</referenceTo>
    <relationshipLabel>Project Resources</relationshipLabel>
    <relationshipName>Project_Resources</relationshipName>
    <type>Lookup</type>
</CustomField>

CloudConsulting/force-app/main/default/objects/Project_Resources__c/fields/RequieredHours__c.field-meta.xml
<CustomField>
    <fullName>RequieredHours__c</fullName>
    <label>RequieredHours</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

CloudConsulting/force-app/main/default/objects/Project_Resources__c/fields/User__c.field-meta.xml
<CustomField>
    <fullName>User__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>User</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Project_Resources</relationshipName>
    <type>Lookup</type>
</CustomField>

CloudConsulting/force-app/main/default/objects/Task__c/Task__c.object-meta.xml
<CustomObject>
    <label>Task</label>
    <nameField>
        <displayFormat>T-{0000}</displayFormat>
        <label>Task Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Tasks</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

CloudConsulting/force-app/main/default/objects/Task__c/fields/EstimatedHours__c.field-meta.xml
<CustomField>
    <fullName>EstimatedHours__c</fullName>
    <label>EstimatedHours</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

CloudConsulting/force-app/main/default/objects/Task__c/fields/Project_Resource__c.field-meta.xml
<CustomField>
    <fullName>Project_Resource__c</fullName>
    <label>Project Resource</label>
    <referenceTo>Project_Resources__c</referenceTo>
    <relationshipLabel>Tasks</relationshipLabel>
    <relationshipName>Tasks</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

CloudConsulting/force-app/main/default/objects/Task__c/fields/WorkedHours__c.field-meta.xml
<CustomField>
    <fullName>WorkedHours__c</fullName>
    <defaultValue>0</defaultValue>
    <label>WorkedHoursTask</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

CloudConsulting/force-app/main/default/classes/WorkloadTest.cls
@isTest
public class WorkloadTest {
	
    @testSetup
    static void createDataTest(){
       
       
       // Creo un Project , un Project line Item y un Proyect Resource
       Project__c proyecto = new Project__c(Name = 'TestProject', ProjectManager__c = UserInfo.getUserId(), Status__c = 'Pre Kickoff', QuantityHours__c = 10, StartDate__c = Date.today(), EndDate__c = Date.today() + 3, Amount__c = 1000, SquadLead__c= UserInfo.getUserId());    
       Insert proyecto;
       Project_Line_Item__c pli = new Project_Line_Item__c(Name= 'pliTest', HoursPerRole__c= 50 , Role__c= 'Developer', Project__c= proyecto.Id);
       insert pli; 
       Project_Resources__c prResource = new Project_Resources__c(Project_Line_Item__c= pli.Id, RequieredHours__c= 10, User__c= UserInfo.getUserId() , Project__c= proyecto.Id, StartDate__c = Date.today(), EndDate__c = Date.today() + 1);        
       insert prResource;
        
       // creo tarea asociada al recurso
       
       Task__c task = new Task__c(
            Status__c = 'In Progress',
            Description__c = 'Test Task',
            StartDate__c = Date.today(),
            EndDate__c = Date.today()+ 1,
            EstimatedHours__c = 5,
            WorkedHours__c = 0,
            Project_Resource__c = prResource.Id
        );
        insert task;
	 
    }
    
    
    @isTest
    static void testGetProject() {
		
        // Llamar al método getProject() y verificar que devuelve los registros correctos
        Test.startTest();
        List<Project_Resources__c> proResource = Workload.getProject();
        Test.stopTest();
		
        List<Project__c> pr =[SELECT Id FROM Project__c WHERE Name = 'TestProject'];
        System.debug(proResource);
        System.debug(pr);
        System.assertEquals(1, proResource.size());
        System.assertEquals(proResource[0].Project__c, pr[0].Id);
        
    }

    @isTest
    static void testGetTask() {
		
        List<Project_Resources__c> prResource = [SELECT Id FROM Project_Resources__c WHERE Project__r.Name= 'TestProject'];
        System.debug(prResource + 'id del recurso de prueba');
        
        // Llamar al método getTask() con el ID del registro de Project_Resources__c y verificar que devuelve los registros correctos
        Test.startTest();
        List<Task__c> taskFromMethod = Workload.getTask(prResource[0].Id);
        Test.stopTest();
		
        List<Task__c> task = [SELECT Id, Status__c FROM Task__c WHERE Description__c= 'Test Task'];
        System.assertEquals(1, taskFromMethod.size());
        System.assertEquals(task[0].Id, taskFromMethod[0].Id);
        System.assertEquals(task[0].Status__c, taskFromMethod[0].Status__c);
        
    }

    @isTest
    static void testUpdateWorkedHours() {
        
        //Obtengo la tarea de prueba para actualizarla mediante el metodo
        List<Task__c> TaskToUpdate =[SELECT Id FROM Task__c WHERE Description__c = 'Test Task'];

        // Llamar al método updateWorkedHours() y verificar que el registro se actualiza correctamente
        Test.startTest();
        Task__c updatedTask = Workload.updateWorkedHours(TaskToUpdate[0].Id, true, 3);
        Test.stopTest();

        System.assertEquals('Completed', updatedTask.Status__c);
        System.assertEquals(3, updatedTask.WorkedHours__c);
    }
    
    @isTest
    static void closeProject() {
        List<Project__c> prToClose = [SELECT Id FROM Project__c WHERE Name = 'TestProject'];
    
        Test.startTest();
        try {
            prToClose[0].Status__c = 'Completed';
            update prToClose;
        } catch(DmlException e) {
            System.debug(e);
            System.assert(e.getMessage().contains('You cannot close a project with a close date different from the current date.'), 'El mensaje de error no es el esperado');
        }
    
        try {
            prToClose[0].Status__c = 'Completed';
            prToClose[0].EndDate__c = Date.today();
            update prToClose;
        } catch(DmlException e2) {
            System.debug(e2);
            System.assert(e2.getMessage().contains('The project cannot be completed until all tasks are finished.'), 'El mensaje de error no es el esperado');
        }
    
        try {
            List<Task__c> task = [SELECT Id FROM Task__c WHERE Description__c = 'Test Task'];  
            Workload.updateWorkedHours(task[0].Id, True, 10);
            prToClose[0].Status__c = 'Completed';
            prToClose[0].EndDate__c = Date.today();
            update prToClose;
            System.assertEquals('Completed', task[0].Status__c);
            System.assertEquals('Completed', prToClose[0].Status__c);
        } catch(Exception e3) {
            System.debug(e3 + 'No esperaba fallo aqui');
        }
    
        Test.stopTest();
    }


}