CloudConsulting/force-app/main/default/objects/Project__c/Project__c.object-meta.xml
<CustomObject>
    <label>Project</label>
    <nameField>
        <label>Project Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Projects</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

CloudConsulting/force-app/main/default/objects/Project_Line_Item__c/Project_Line_Item__c.object-meta.xml
<CustomObject>
    <label>Project Line Item</label>
    <nameField>
        <label>Project Line Item Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Project Line Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

CloudConsulting/force-app/main/default/objects/Project_Line_Item__c/fields/HoursPending__c.field-meta.xml
<CustomField>
    <fullName>HoursPending__c</fullName>
    <formula>HoursPerRole__c -  HoursAllocated__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>HoursPending</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

CloudConsulting/force-app/main/default/objects/Project_Resources__c/Project_Resources__c.object-meta.xml
<CustomObject>
    <label>Project Resource</label>
    <nameField>
        <displayFormat>PR-{0000}</displayFormat>
        <label>Project Resources Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Project Resources</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

CloudConsulting/force-app/main/default/objects/Project_Resources__c/fields/Project__c.field-meta.xml
<CustomField>
    <fullName>Project__c</fullName>
    <label>Project</label>
    <referenceTo>Project__c</referenceTo>
    <relationshipLabel>Project Resources</relationshipLabel>
    <relationshipName>Project_Resources</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

CloudConsulting/force-app/main/default/objects/Project_Resources__c/fields/Project_Line_Item__c.field-meta.xml
<CustomField>
    <fullName>Project_Line_Item__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Project Line Item</label>
    <referenceTo>Project_Line_Item__c</referenceTo>
    <relationshipLabel>Project Resources</relationshipLabel>
    <relationshipName>Project_Resources</relationshipName>
    <type>Lookup</type>
</CustomField>

CloudConsulting/force-app/main/default/objects/Project_Resources__c/fields/RequieredHours__c.field-meta.xml
<CustomField>
    <fullName>RequieredHours__c</fullName>
    <label>RequieredHours</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

CloudConsulting/force-app/main/default/objects/Project_Resources__c/fields/User__c.field-meta.xml
<CustomField>
    <fullName>User__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>User</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Project_Resources</relationshipName>
    <type>Lookup</type>
</CustomField>

CloudConsulting/force-app/main/default/classes/resourcesAllocationTrigger.cls
public with sharing class resourcesAllocationTrigger {

    public static List <Project_Resources__c> resourcesRejected = new List <Project_Resources__c>();
    public static List <Project_Resources__c> resourcesApproved = new List <Project_Resources__c>();

    public static List <Project_Resources__c> validateResources (List <Project_Resources__c> resourcesList ){
    
        //Create a Set Id of the resources
        Set <String> resourcesIds = new Set <String>();
        String projectId = resourcesList[0].Project__c;
        String pliId = resourcesList[0].Project_Line_Item__c;
        Decimal sumHours = 0;
        System.debug('Id del proyecto ' + projectId);
        for(Project_Resources__c rid : resourcesList){
            resourcesIds.add(rid.User__c);
            sumHours += rid.RequieredHours__c;
        }

        //Find the project
        Project__c project =
        [
        SELECT StartDate__c, EndDate__c
        FROM Project__c
        WHERE Id = : projectId
        ];

        Project_Line_Item__c pendingHours =
                            [
                            SELECT HoursPending__c
                            FROM Project_Line_Item__c
                            WHERE Id =: pliId
                            ];
        
        System.debug('Id del pli ' + pliId);
        System.debug('Horas Pendientes ' + pendingHours.HoursPending__c);
        System.debug('Horas Alocadas ' + sumHours);
        //Bring all the projects where the user is allocated
        List <Project_Resources__c> projectList = 
                            [
                            SELECT User__c, StartDate__c, EndDate__c
                            FROM Project_Resources__c
                            WHERE User__c IN : resourcesIds
                            ];

        Date projectStartDate = project.StartDate__c;
        Date projectEndDate = project.EndDate__c;

        System.debug('Inicio ' + projectStartDate + ' Fin ' + projectEndDate);

        
        //Inspect the Resource List of all the users that are going to be allocated
        if(pendingHours.HoursPending__c<sumHours){
            
            /*Project_Resources__c hoursExceeded = New Project_Resources__c();
            hoursExceeded.RequieredHours__c = -1;
            hoursExceeded.Project__c = resourcesList[0].Project__c;
            hoursExceeded.Project_Line_Item__c = resourcesList[0].Project_Line_Item__c;*/

            resourcesList[0].RequieredHours__c = 5;
            
            System.debug('Horas en exceso ' + resourcesList[0].RequieredHours__c);
            resourcesRejected.add(resourcesList[0]);
        }else{
        
        for(Project_Resources__c prnew : resourcesList){
            Boolean available = true;

            if(prNew.StartDate__c < projectStartDate || prNew.EndDate__c > projectEndDate){
                resourcesRejected.add(prNew);                
                available = false;
            } else {

                for(Project_Resources__c prold : projectList ){
                    if(prnew.User__c == prold.User__c){
                        Boolean validate = validateAvailability(prold,prnew);
                        if(!validate){
                            available = false;
                            break;
                        }
                    }
                }
            }
            //If there is no overlaping with another project add to the approved list
            if(available) resourcesApproved.add(prnew);
        }
    }
        return resourcesRejected;
    }

    private static Boolean validateAvailability(Project_Resources__c prOld, Project_Resources__c prNew){
        Boolean validate = true;
          if (prNew.StartDate__c >= prOld.StartDate__c && prNew.StartDate__c <= prOld.EndDate__c) {
            resourcesRejected.add(prNew);            
            validate = false;
          } else if(prNew.EndDate__c >= prOld.StartDate__c && prNew.EndDate__c <= prOld.EndDate__c) {
            resourcesRejected.add(prNew);            
            validate = false;
          } else if(prNew.EndDate__c < prNew.StartDate__c){
            resourcesRejected.add(prNew);            
            validate = false;
          } else if(prNew.EndDate__c == NULL || prNew.StartDate__c == NULL){
            System.debug('Fecha NULL');
            resourcesRejected.add(prNew);            
            validate = false;
          } 
          return validate;
    }

}