CloudConsulting/force-app/main/default/objects/Project_Resources__c/Project_Resources__c.object-meta.xml
<CustomObject>
    <label>Project Resource</label>
    <nameField>
        <displayFormat>PR-{0000}</displayFormat>
        <label>Project Resources Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Project Resources</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

CloudConsulting/force-app/main/default/objects/Project_Resources__c/fields/HoursAllocated__c.field-meta.xml
<CustomField>
    <fullName>HoursAllocated__c</fullName>
    <label>HoursAllocated</label>
    <summarizedField>Task__c.EstimatedHours__c</summarizedField>
    <summaryForeignKey>Task__c.Project_Resource__c</summaryForeignKey>
    <summaryOperation>sum</summaryOperation>
    <type>Summary</type>
</CustomField>

CloudConsulting/force-app/main/default/objects/Project_Resources__c/fields/RequieredHours__c.field-meta.xml
<CustomField>
    <fullName>RequieredHours__c</fullName>
    <label>RequieredHours</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

CloudConsulting/force-app/main/default/objects/Task__c/Task__c.object-meta.xml
<CustomObject>
    <label>Task</label>
    <nameField>
        <displayFormat>T-{0000}</displayFormat>
        <label>Task Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Tasks</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

CloudConsulting/force-app/main/default/objects/Task__c/fields/EstimatedHours__c.field-meta.xml
<CustomField>
    <fullName>EstimatedHours__c</fullName>
    <label>EstimatedHours</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

CloudConsulting/force-app/main/default/objects/Task__c/fields/Project_Resource__c.field-meta.xml
<CustomField>
    <fullName>Project_Resource__c</fullName>
    <label>Project Resource</label>
    <referenceTo>Project_Resources__c</referenceTo>
    <relationshipLabel>Tasks</relationshipLabel>
    <relationshipName>Tasks</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

CloudConsulting/force-app/main/default/classes/assingTaskTrigger.cls
public with sharing class assingTaskTrigger {

    public static List <Task__c> taskRejected = new List <Task__c>();

    public static List <Task__c> validateTask (List <Task__c> taskList ){
        
        Set <String> projectResourcesIds = new Set <String>();
        
        for(Task__c prTask : taskList){
            projectResourcesIds.add(prTask.Project_Resource__c);
        }

        Map<Id, Project_Resources__c> taskMap = New Map<Id, Project_Resources__c>([SELECT
                                                    RequieredHours__c,
                                                    HoursAllocated__c
                                                    FROM Project_Resources__c
                                                    WHERE Id IN : projectResourcesIds]);

        for(Task__c prTask : taskList){
            Decimal requiered = taskMap.get(prTask.Project_Resource__c).RequieredHours__c;
            Decimal allocated = taskMap.get(prTask.Project_Resource__c).HoursAllocated__c;
            Decimal pending = requiered - allocated;
            if(prTask.EstimatedHours__c > pending){
                taskRejected.add(prTask);
            }else if(prTask.EstimatedHours__c < 0){
                taskRejected.add(prTask);
            }else if(prTask.EstimatedHours__c == NULL){
                taskRejected.add(prTask);
            }else if(prTask.Description__c == '' || prTask.Description__c == NULL){
                taskRejected.add(prTask);
            }
        }

        return taskRejected;
    }
}